version: '3.7'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "zaq1@WSX"
    ports:
      - "1433:1433"
  api:
    build:
      context: .
      dockerfile: TagManage.API/Dockerfile
    depends_on:
      - db
    ports:
      - "5000:8080"
      - "5001:80" 
