version: '3.8'

services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123!"
    ports:
      - "1433:1433"
  api:
    build:
      context: .
      dockerfile: TagManage.API/Dockerfile
    environment:
      ConnectionStrings__Default: "Server=db;Database=TagManageDb;User=sa;Password=Password123!;"
    depends_on:
      - db
    ports:
      - "5000:80"
